[package]
name = "bulletproof"
version = "2.0.1"
authors = [
    "Omer <omer@kzencorp.com>",
]

[lib]
crate-type = ["lib"]

[dependencies]
curv = { git = "https://github.com/DrewZt/curv", tag = "v2.0.1",  features =  ["ec_secp256k1"]}
sha2 = "0.8.0"
itertools = "0.7.8"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "range_proof"
path = "benches/range_proof.rs"
harness = false
